//
// Generated file, do not edit! Created by nedtool 6.0 from apps/PingPong/packets/PingPongPacket.msg.
//

#ifndef __PINGPONGPACKET_M_H
#define __PINGPONGPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



class PingPongPacket;
#include "nodes/mec/MECPlatform/MECPackets_m.h" // import nodes.mec.MECPlatform.MECPackets

/**
 * Class generated from <tt>apps/PingPong/packets/PingPongPacket.msg:19</tt> by nedtool.
 * <pre>
 * class PingPongPacket extends MECPacket
 * {
 *     int ueOmnetID;
 *     string data;
 * }
 * </pre>
 */
class PingPongPacket : public ::MECPacket
{
  protected:
    int ueOmnetID = 0;
    omnetpp::opp_string data;

  private:
    void copy(const PingPongPacket& other);

  protected:
    bool operator==(const PingPongPacket&) = delete;

  public:
    PingPongPacket();
    PingPongPacket(const PingPongPacket& other);
    virtual ~PingPongPacket();
    PingPongPacket& operator=(const PingPongPacket& other);
    virtual PingPongPacket *dup() const override {return new PingPongPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getUeOmnetID() const;
    virtual void setUeOmnetID(int ueOmnetID);
    virtual const char * getData() const;
    virtual void setData(const char * data);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PingPongPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PingPongPacket& obj) {obj.parsimUnpack(b);}

#endif // ifndef __PINGPONGPACKET_M_H

